package bluehearthealthcare.com.aadhaarapp;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.CompoundButton;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.TextView;
import android.widget.Toast;

import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.zxing.integration.android.IntentIntegrator;
import com.google.zxing.integration.android.IntentResult;

import java.util.HashMap;
import java.util.Map;

public class MainActivity extends AppCompatActivity {
    EditText ed1,ed2,ed3,ed4,ed5;
    ImageView iv;
    Button sub;
    RadioButton rb1,rb2;
    RadioGroup rg;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        iv=findViewById(R.id.print);
        sub=findViewById(R.id.submit);
        sub.setVisibility(View.GONE);
        ed1=findViewById(R.id.name);
        ed2=findViewById(R.id.dob);
        ed3=findViewById(R.id.aadhaar_no);
        ed4=findViewById(R.id.mobile);
        ed5=findViewById(R.id.text_criminal);
//        rb1=findViewById(R.id.yes);
//        rb2=findViewById(R.id.no);
//        rb1.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
//            @Override
//            public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
//                if(isChecked)
//                {
//                    ed5.setVisibility(View.VISIBLE);
//                }
//            }
//        });
//        rb2.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
//            @Override
//            public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
//                if(isChecked)
//                {
//                    ed5.setVisibility(View.GONE);
//                }
//            }
//        });
        iv.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                IntentIntegrator integrator = new IntentIntegrator(MainActivity.this);
                integrator.setDesiredBarcodeFormats(IntentIntegrator.QR_CODE_TYPES);
                integrator.setPrompt("Scan QR code generated by sender");
                integrator.setBeepEnabled(true);
                integrator.setCameraId(0);
                integrator.setOrientationLocked(false);
                integrator.setBarcodeImageEnabled(false);
                integrator.initiateScan();
            }
        });
    }
    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        final IntentResult result = IntentIntegrator.parseActivityResult(requestCode, resultCode, data);
        if (result != null) {
            if (result.getContents() == null) {
                sub.setVisibility(View.GONE);
                Toast.makeText(this, "You have cancelled the scanning", Toast.LENGTH_SHORT).show();
            } else {
                sub.setVisibility(View.VISIBLE);
                Toast.makeText(this, "" + result.getContents(), Toast.LENGTH_SHORT).show();
                sub.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        FirebaseDatabase database = FirebaseDatabase.getInstance();
                        DatabaseReference myRef = database.getReference("Database");
                        String a1=ed1.getText().toString();
                        String a2=ed2.getText().toString();
                        String a3=ed3.getText().toString();
                        String a4=ed4.getText().toString();
                        Map<String,String> users = new HashMap<>();
                        users.put("Name", a1);
                        users.put("DOB", a2);
                        users.put("Aadhaar No", a3);
                        users.put("Mobile", a4);
                        myRef.child(result.getContents()).setValue(users);
//                        if(rb1.isChecked())
//                        {
//                            users.put("Criminal","Yes");
//                            users.put("Criminal Description",ed5.getText().toString());
//                        }
//                        else
//                        {
//                            users.put("Criminal","No");
//                        }
                    }
                });
            }
        }
        super.onActivityResult(requestCode, resultCode, data);
    }
}
