package bluehearthealthcare.com.aadhaarapp;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.Toast;

import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.zxing.integration.android.IntentIntegrator;
import com.google.zxing.integration.android.IntentResult;

import java.text.DateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

public class Record extends AppCompatActivity {
    EditText ed1,ed2,ed3;
    ImageView print;
    Button sub1;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_record);
        ed1=findViewById(R.id.text_criminal1);
        ed2=findViewById(R.id.text_criminal2);
        ed3=findViewById(R.id.text_criminal3);
        print=findViewById(R.id.print1);
        sub1=findViewById(R.id.submit_crime);
        print.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                IntentIntegrator integrator = new IntentIntegrator(Record.this);
                integrator.setDesiredBarcodeFormats(IntentIntegrator.QR_CODE_TYPES);
                integrator.setPrompt("Scan QR code generated by sender");
                integrator.setBeepEnabled(true);
                integrator.setCameraId(0);
                integrator.setOrientationLocked(false);
                integrator.setBarcodeImageEnabled(false);
                integrator.initiateScan();
            }
        });
    }
    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        final IntentResult result = IntentIntegrator.parseActivityResult(requestCode, resultCode, data);
        if (result != null) {
            if (result.getContents() == null) {
                Toast.makeText(this, "You have cancelled the scanning", Toast.LENGTH_SHORT).show();
            } else {
                Toast.makeText(this, "" + result.getContents(), Toast.LENGTH_SHORT).show();
                sub1.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        FirebaseDatabase database = FirebaseDatabase.getInstance();
                        DatabaseReference myRef = database.getReference("Database");
                        String key= myRef.child(result.getContents()).child("Criminal Record").push().getKey();
                        String a1=ed1.getText().toString();
                        String a2=ed2.getText().toString();
                        String a3=ed3.getText().toString();
                        Map<String,String> users = new HashMap<>();
                        users.put("Crime", a1);
                        users.put("Area", a2);
                        users.put("Penalty", a3);
                        String ts = DateFormat.getDateTimeInstance().format(new Date());
                        myRef.child(result.getContents()).child("Criminal Record").child(ts).setValue(users);
                    }
                });
            }
        }
        super.onActivityResult(requestCode, resultCode, data);
    }
}
