package bluehearthealthcare.com.aadhaarapp;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;
import android.widget.Toast;

import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;
import com.google.zxing.integration.android.IntentIntegrator;
import com.google.zxing.integration.android.IntentResult;

import java.util.HashMap;
import java.util.Map;

public class Show extends AppCompatActivity {
TextView name,dob,adno,mobno,crimanal,desc,decView;
Button sc;
LinearLayout subb;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_show);
        name=findViewById(R.id.name_);
        adno=findViewById(R.id.aadhaar_no);
        dob=findViewById(R.id.dob_d);
        mobno=findViewById(R.id.mob);
        sc=findViewById(R.id.button_scan);
        subb=findViewById(R.id.layout);
        subb.setVisibility(View.GONE);
        desc=findViewById(R.id.criminaldesc);
        crimanal=findViewById(R.id.criminalRecord);
        decView=findViewById(R.id.view);
        sc.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                IntentIntegrator integrator = new IntentIntegrator(Show.this);
                integrator.setDesiredBarcodeFormats(IntentIntegrator.QR_CODE_TYPES);
                integrator.setPrompt("Scan QR code generated by sender");
                integrator.setBeepEnabled(true);
                integrator.setCameraId(0);
                integrator.setOrientationLocked(false);
                integrator.setBarcodeImageEnabled(false);
                integrator.initiateScan();
            }
        });
    }
    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        final IntentResult result = IntentIntegrator.parseActivityResult(requestCode, resultCode, data);
        if (result != null) {
            if (result.getContents() == null) {
                subb.setVisibility(View.GONE);
                Toast.makeText(this, "You have cancelled the scanning", Toast.LENGTH_SHORT).show();
            } else {
                subb.setVisibility(View.VISIBLE);
                Toast.makeText(this, "" + result.getContents(), Toast.LENGTH_SHORT).show();
                        FirebaseDatabase.getInstance().getReference("Database").child(result.getContents()).addValueEventListener(new ValueEventListener() {
                            @Override
                            public void onDataChange(DataSnapshot dataSnapshot) {
                                if (dataSnapshot.hasChildren()) {
                                    String a1 = dataSnapshot.child("Name").getValue(String.class);
                                    String a2 = dataSnapshot.child("DOB").getValue(String.class);
                                    String a3 = dataSnapshot.child("Aadhaar No").getValue(String.class);
                                    String a4 = dataSnapshot.child("Mobile").getValue(String.class);
                                    name.setText(a1);
                                    adno.setText(a2);
                                    dob.setText(a3);
                                    mobno.setText(a4);
                                    if(dataSnapshot.child("Criminal Record").hasChildren())
                                    {
                                        String val="";
                                        for (DataSnapshot snapshot:dataSnapshot.child("Criminal Record").getChildren())
                                        {
                                            String value=snapshot.child("Area").getValue(String.class);
                                            val=val+"Area:"+value+"\n";
                                            value=snapshot.child("Crime").getValue(String.class);
                                            val=val+"Crime:"+value+"\n";
                                            value=snapshot.child("Penalty").getValue(String.class);
                                            val=val+"Penalty:"+value+"\n";
                                            value=snapshot.child("TimeStamp").getValue(String.class);
                                            val=val+"Time:"+value+"\n\n";
                                        }
                                        desc.setText(val);
                                        desc.setVisibility(View.VISIBLE);
                                        decView.setText("Yes");
                                        decView.setVisibility(View.VISIBLE);
                                    }
                                    else
                                    {
                                        desc.setVisibility(View.GONE);
                                        decView.setVisibility(View.GONE);
                                    }
                                }
                                else
                                {
                                    Toast.makeText(Show.this, "No such fingerprint", Toast.LENGTH_SHORT).show();
                                }
                            }

                            @Override
                            public void onCancelled(DatabaseError databaseError) {
                                Toast.makeText(Show.this, "" + databaseError, Toast.LENGTH_SHORT).show();
                            }

                });
            }
        }
        super.onActivityResult(requestCode, resultCode, data);
    }
}
